apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/nginx
    readOnly: true
    server: 172.31.32.33
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-nfs-storage-retain
  volumeMode: Filesystem
