apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-nfs-storage-retain
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
